plugins:
  - jest

env:
  es2020: true
  node: true

extends:
  - airbnb-base
  - plugin:jest/recommended

parser: '@babel/eslint-parser'

parserOptions:
  ecmaVersion: 13
  sourceType: module
  requireConfigFile: false

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
